# Hugo variables
#
baseurl = "https://nuhil.net/"
languageCode = "en-us"
title = "Nuhil Mehdy"
theme = "nuhil"
# number of posts to show on home/category/tag pages (Default: 10)
paginate = 5
# optionally override the site's footer with custom copyright text
copyright = "&copy; Except where otherwise noted, content on this site is licensed under a [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)."
googleAnalytics = "UA-107718367-1"
disqusShortname = "nuhil"

[permalinks]
  post = "/:year/:month/:title/"
  page = "/:slug/"

[[menu.sidebar]]
  name = "ডাটা সায়েন্সের ভিত্তি"
  url = "https://ds.howtocode.com.bd"  

[[menu.sidebar]]
  name = "iOS প্রোগ্রামিং উইথ সুইফট"
  url = "https://ios.howtocode.com.bd"    

[[menu.sidebar]]
  name = "ডিপ লার্নিং ও আর্টিফিশিয়াল নিউরাল নেটওয়ার্ক"
  url = "https://dl.howtocode.com.bd"  

[[menu.sidebar]]
  name = "বাংলায় পাইথন প্রোগ্রামিং"
  url = "https://python.howtocode.com.bd"  

# custom navbar menu entry.   See the custom_navbar parameter below for
# details.

#[[menu.navbar]]
#  name = "Link 1"
#  url = "https://example.org"


# Theme variables
#
[params]
  # Site author
  author = "Nuhil Mehdy"

  # Description/subtitle for homepage (can be Markdown)
  description = "Polyglot Programmer, White Hat Hacker, AI Enthusiast by Choice!"

  # Format dates with Go's time formatting
  date_format = "Mon Jan 02, 2006"

  # verification string for Google Webmaster Tools
  #google_verify_meta = "BAi57DROASu4b2mkVNA_EyUsobfA7Mq8BmSg7Rn-Zp9"

  # verification string for Bing Webmaster Tools
  #bing_verify_meta = "3DA353059F945D1AA256B1CD8A3DA847"

  # verification string for Yandex Webmaster Tools
  #yandex_verify_meta = "66b077430f35f04a"

  # Optionally display a message about the site's use of cookies, which may be
  # required for your site in the European Union. Set the parameter below to a
  # page where the user can get more information about cookies, either on your
  # site or externally, for example:
  # cookie_consent_info_url = "/cookie-information/"
  cookie_consent_info_url = "http://cookiesandyou.com"

  # customise the contents of the navbar at the top of the page.  The default
  # behaviour is to list all static pages not in the posts directory. When the
  # parameter below is set to true you will have to manually add entries to the
  # navbar, either by adding the following menu variable to the front matter of
  # the relevant pages
  #   menu = "navbar"
  # or by specifying menu entries in a similar way to the sidebar menu above.
  #custom_navbar = true

  # show sharing icons on pages/posts (default: true)
  #sharingicons = true

  # Display post summaries instead of content in list templates (default: true)
  # truncate = false

  # Disable the use of sub-resource integrity on CSS/JS assets (default: false)
  # Useful if you're using a CDN or other host where you can't control cache headers
  #disable_sri = false

  [params.sidebar]
    # Optional about block for sidebar (can be Markdown)
    about = "PhD student of `Cyber Security` with prior graduation in Computer Science, and former Software Engineer with more than 5 years of experience who believes in `Artificial Intelligence` and likes the `Unix` environment for developing API Centric & Back End Apps in `Python`, `PHP` and, `Java` ecosystem; considering `MEAN` as a robust stack & finds fun in Mobile App Development with `Swift` & `Kotlin` for iOS & Android preserving cool `UI/UX` & Security. [Read More](/about)"

    # How many posts to show on the sidebar (Default: 5)
    #num_recent_posts = 2

  [params.social]
    # Optional, used for attribution in Twitter cards (ideally not a person
    # for example: nytimes, flickr, NatGeo, etc).
    # See: https://dev.twitter.com/cards/types/summary-large-image
    twitter = "nuhil"

# Default content language for Hugo 0.17's multilingual support (default is "en")
# See: https://github.com/spf13/hugo/blob/master/docs/content/content/multilingual.md
#DefaultContentLanguage = "en"

# Languages to render
#[languages.en]
#[languages.bg]

# vim: ts=2 sw=2 et

pygmentsCodeFences = true